### ISSUE TITLE
关于这个项目的进展与开发完成度？

### ISSUE THREAD

**Issue by xiaomaimuchanyiyiba** [oldratlee/land#19]
请问这个库的完成度是多少？

**Comment by oldratlee** [comment]
@xiaomaimuchanyiyiba 谢谢你的关注 ♥️

这个项目并没有 按好的节奏完成刚开始设立的 [目标们](https://github.com/oldratlee/land#beer-%E7%9B%AE%E6%A0%87) 😂，
实际上进展、效果是 完成了关于`ClassLoader`主题的自学、练习与资料整理。

在文档中加了一节 [已有的基于ClassLoader实现的隔离容器项目](https://github.com/oldratlee/land#%E5%B7%B2%E6%9C%89%E7%9A%84%E5%9F%BA%E4%BA%8Eclassloader%E5%AE%9E%E7%8E%B0%E7%9A%84%E9%9A%94%E7%A6%BB%E5%AE%B9%E5%99%A8%E9%A1%B9%E7%9B%AE)

-------------------

> ## 已有的基于ClassLoader实现的隔离容器项目
> 
> - [`jboss-modules`](https://github.com/jboss-modules/jboss-modules)  
>     JBoss Modules is a standalone implementation of a modular (non-hierarchical) class loading and execution environment for Java.
> - [`sofa-jarslink`](https://github.com/sofastack/sofa-jarslink)  
>     Jarslink is a sofa ark plugin used to manage multi-application deployment
>
> [目标们](https://github.com/oldratlee/land#beer-%E7%9B%AE%E6%A0%87)
> 
> # :beer: 目标
> 
> * 给出类加载委托情况的完备说明
> * 给出类加载委托规则的规范描述
> * 给出类加载委托规则的规范描述的自己的一个描述格式  
> 对于这个项目会优先使用`Properties`来描述，简单够用。
> * 说明`Java`的`ClassLoader`的用途和限制
> * 给出`ClassLoader`使用和实现的原则
> * `ClassLoader`使用和实现容易出错的地方
> * 整理出使用了`ClassLoader`的常见框架
> * 说明这些框架中`ClassLoader`的实现方法及其使用契约
> * 给出`ClassLoader`实现方法及其使用契约的最佳实践
> 
> # :loudspeaker: 进阶目标
> 
> * `Web`容器集成
> * 实现`OSGi`规范    
> 这个也可以用来验证实现是否面向编程友好
